param (
    [string]$ProjectRoot = (Get-Location).Path,
    [string]$OutputFile = "docs/CODE_INDEX.md"
)

$ErrorActionPreference = "Stop"

# --- CONFIGURATION ---
# Directories to scan for code files
$scanDirs = @(
    @{ Name = "Backend"; Path = "backend"; Extensions = @("*.ts", "*.js", "*.py") },
    @{ Name = "Frontend"; Path = "frontend"; Extensions = @("*.tsx", "*.jsx", "*.vue") },
    @{ Name = "Database"; Path = "migrations"; Extensions = @("*.sql") },
    @{ Name = "Database"; Path = "supabase/migrations"; Extensions = @("*.sql") },
    @{ Name = "Scripts"; Path = "scripts"; Extensions = @("*.ps1", "*.sh") }
)

# Files/folders to exclude
$excludePatterns = @("node_modules", ".git", "dist", "build", ".next", "__pycache__")

# ---------------------

function Get-FileDescription {
    param ([string]$FilePath)
    
    $content = Get-Content $FilePath -TotalCount 20 -ErrorAction SilentlyContinue
    if (-not $content) { return "-" }
    
    # Try to extract a description from comments or exports
    foreach ($line in $content) {
        if ($line -match "^//\s*(.+)$" -or $line -match "^#\s*(.+)$" -or $line -match "^--\s*(.+)$") {
            return $matches[1].Trim().Substring(0, [Math]::Min(50, $matches[1].Trim().Length))
        }
        if ($line -match "export\s+(default\s+)?(function|class|const)\s+(\w+)") {
            return "Exports: $($matches[3])"
        }
    }
    return "-"
}

function Get-ComponentName {
    param ([string]$FilePath)
    return [System.IO.Path]::GetFileNameWithoutExtension($FilePath)
}

# --- MAIN ---
Write-Host "Generating Code Index..." -ForegroundColor Cyan
Write-Host "Project Root: $ProjectRoot" -ForegroundColor Gray

$output = @()
$output += "# 🗂️ Code Index"
$output += ""
$output += "> Auto-generated index of project code files. Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
$output += ""
$output += "---"

foreach ($dir in $scanDirs) {
    $fullPath = Join-Path $ProjectRoot $dir.Path
    
    if (-not (Test-Path $fullPath)) {
        continue
    }
    
    $files = @()
    foreach ($ext in $dir.Extensions) {
        $found = Get-ChildItem -Path $fullPath -Filter $ext -Recurse -File -ErrorAction SilentlyContinue |
        Where-Object { 
            $path = $_.FullName
            $exclude = $false
            foreach ($pattern in $excludePatterns) {
                if ($path -like "*$pattern*") { $exclude = $true; break }
            }
            -not $exclude
        }
        $files += $found
    }
    
    if ($files.Count -eq 0) { continue }
    
    $output += ""
    $output += "## $($dir.Name)"
    $output += ""
    $output += "| Component | Path | Description |"
    $output += "|-----------|------|-------------|"
    
    foreach ($file in $files | Sort-Object FullName) {
        $relativePath = $file.FullName.Substring($ProjectRoot.Length).TrimStart('\', '/')
        $name = Get-ComponentName -FilePath $file.FullName
        $desc = Get-FileDescription -FilePath $file.FullName
        $output += "| $name | ``/$relativePath`` | $desc |"
    }
}

$output += ""
$output += "---"
$output += ""
$output += "> **Note**: This file is auto-generated by ``scripts/generate_code_index.ps1``."

$outputPath = Join-Path $ProjectRoot $OutputFile
$outputDir = Split-Path $outputPath
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$output | Set-Content $outputPath -Encoding utf8
Write-Host "SUCCESS: Code Index generated at $outputPath" -ForegroundColor Green
Write-Host "Found $($files.Count) files." -ForegroundColor Gray
